# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  l_arm_joint:
    has_velocity_limits: true
    max_velocity: 55.25
    has_acceleration_limits: false
    max_acceleration: 0
  l_elbow_joint:
    has_velocity_limits: true
    max_velocity: 55.25
    has_acceleration_limits: false
    max_acceleration: 0
  l_finger_joint:
    has_velocity_limits: true
    max_velocity: 55.25
    has_acceleration_limits: false
    max_acceleration: 0
  l_hand_joint:
    has_velocity_limits: true
    max_velocity: 55.25
    has_acceleration_limits: false
    max_acceleration: 0
  l_shoulder_joint:
    has_velocity_limits: true
    max_velocity: 55.25
    has_acceleration_limits: false
    max_acceleration: 0
  l_wrist_joint:
    has_velocity_limits: true
    max_velocity: 55.25
    has_acceleration_limits: false
    max_acceleration: 0
  neckro_joint:
    has_velocity_limits: true
    max_velocity: 55.25
    has_acceleration_limits: false
    max_acceleration: 0
  necktilt_joint:
    has_velocity_limits: true
    max_velocity: 55.25
    has_acceleration_limits: false
    max_acceleration: 0
  neckud_joint:
    has_velocity_limits: true
    max_velocity: 55.25
    has_acceleration_limits: false
    max_acceleration: 0
  r_arm_joint:
    has_velocity_limits: true
    max_velocity: 55.25
    has_acceleration_limits: false
    max_acceleration: 0
  r_elbow_joint:
    has_velocity_limits: true
    max_velocity: 55.25
    has_acceleration_limits: false
    max_acceleration: 0
  r_finger_joint:
    has_velocity_limits: true
    max_velocity: 55.25
    has_acceleration_limits: false
    max_acceleration: 0
  r_hand_joint:
    has_velocity_limits: true
    max_velocity: 55.25
    has_acceleration_limits: false
    max_acceleration: 0
  r_shoulder_joint:
    has_velocity_limits: true
    max_velocity: 55.25
    has_acceleration_limits: false
    max_acceleration: 0
  r_wrist_joint:
    has_velocity_limits: true
    max_velocity: 55.25
    has_acceleration_limits: false
    max_acceleration: 0
  upperbody_joint:
    has_velocity_limits: true    
    max_velocity: 55.25
    has_acceleration_limits: false
    max_acceleration: 0
